name: blog_todoapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  equatable: ^2.0.7
  flutter_slidable: ^4.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/applogo/todo.png
 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/applogo/todo.png"
  min_sdk_android: 21 
  